# Generated by Django 4.2 on 2023-05-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentstep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.CharField(max_length=255)),
                ('cardnumber', models.IntegerField()),
                ('expirationdate', models.DateTimeField()),
                ('cvc', models.IntegerField()),
            ],
        ),
    ]
