# Generated by Django 4.2 on 2023-05-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_paymentstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='checkout',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.country'),
        ),
    ]
