# Generated by Django 4.2 on 2023-05-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_country_alter_checkout_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstep',
            name='expirationdate',
            field=models.DateField(),
        ),
    ]
